{
  "MD013": false,
  "MD022": true,
  "MD025": true,
  "MD004": false,
  "MD029": false,
  "MD040": true,
  "MD041": false,
  "MD036": false,
  "MD033": false,
  "MD034": false,
  "MD024": false,
  "MD026": false,
}
