keys:
  - &larsg age1w7stgltn2stl94ap045qrzufmy9x9wuqnzrlug60v58g5j8m6c3qym8uxy
  - &project_workflow age1m0yvecwtwm603lj656efg3utzv9pdwehdmufrvey0mtraq3vhetq8y84k0

creation_rules:
  # Project administration
  - path_regex: ^project/secrets.yaml$
    key_groups:
      - age:
          - *larsg
          - *project_workflow
