# This is a "secret" access token for GitHub
# it's scoped to be on par with any other public
# user, so nothing, too, dangerous comes from it.
# It's a simple solution to avoid having to setup a key distribution
# mechanism. And required for some of FluxCD's components as authentication.
---
apiVersion: v1
data:
  password: Z2l0aHViX3BhdF8xMUE3U1laM0kwV21kM2RUWUI3ZDRPX0QxcHc3WFo3ZzJlWmxWcXhZcmFZYUJkYjNkWDNSelNhbkM5RHF5S0k5MmVSQkg1Q1VDR0s2YUdmZ1Nx
kind: Secret
metadata:
  creationTimestamp: null
  name: flux-system
  namespace: flux-system