# yaml-language-server: $schema=https://raw.githubusercontent.com/rancher/k3d/main/pkg/config/config.versions.schema.json

# See link for documentation: https://k3d.io/v5.8.3/usage/configfile/
apiVersion: k3d.io/v1alpha5
kind: Simple
servers: ${server_count}
agents: ${agent_count}
kubeAPI:
  hostIP: ${cluster_ip}
  hostPort: "${cluster_port}"
image: rancher/k3s:${k3s_version}
ports:
  - port: ${host_lb_port}:${cluster_lb_port}
    nodeFilters:
      - loadbalancer
# See link for documentation: https://docs.k3s.io/installation/private-registry
registries:
  create:
    name: ${registry_name}
    host: ${registry_ip}
    hostPort: "${registry_port}"
    volumes:
      - /tmp/reg:/var/lib/registry
  config: |
    mirrors:
      "*":
        endpoint:
          - "http://registry.localhost:${registry_port}"
